environment        = "dev"
resource_group_name = "landgriffonmanual-rg"
location = "West Europe"
storage_account_name = "landgriffonsa"
storage_container_name = "landgriffon"
# tf_state_bucket    = "landgriffon-tf-state"
# allowed_account_id = "622152552144"
# domain             = "landgriffon.com"
# rds_engine_version = "13.2"

