# GH Actions runners on Ubuntu 18.04 require an older (<= 3.6) Compose file version
version: "3.6"
services:
  api:
    build:
      context: ./api
      dockerfile: api.Dockerfile
    container_name: marxan-test-unit-api
    command: test-unit
    user: "5000:5000"
    volumes:
      - ./api/apps:/opt/marxan-api/apps
      - ./api/libs:/opt/marxan-api/libs
    environment:
      - NODE_PATH=src
      - NODE_ENV=test
      - NODE_CONFIG_DIR=apps/api/config
      - API_POSTGRES_URL=postgres://${API_POSTGRES_USER}:${API_POSTGRES_PASSWORD}@marxan-postgresql-api:5432/${API_POSTGRES_DB}
      - GEO_POSTGRES_URL=postgres://${GEO_POSTGRES_USER}:${GEO_POSTGRES_PASSWORD}@marxan-postgresql-geo-api:5432/${GEO_POSTGRES_DB}

  geoprocessing:
    build:
      context: ./api
      dockerfile: geo.Dockerfile
    container_name: marxan-test-unit-geoprocessing
    command: test-unit
    user: "5000:5000"
    volumes:
      - ./api/apps:/opt/marxan-geoprocessing/apps
      - ./api/libs:/opt/marxan-geoprocessing/libs
    environment:
      - NODE_PATH=src
      - NODE_ENV=test
      - NODE_CONFIG_DIR=apps/geoprocessing/config
