# GH Actions runners on Ubuntu 18.04 require an older (<= 3.6) Compose file version
version: "3.6"
services:
  api:
    build:
      context: ./api
      dockerfile: api.Dockerfile
      args:
        UID: 5000
        GID: 5000
        UPLOADS_TEMP_DIR: "/tmp/storage"
    container_name: marxan-test-unit-api
    command: test-unit
    user: "5000:5000"
    volumes:
      - ./api/apps:/opt/marxan-api/apps
      - ./api/libs:/opt/marxan-api/libs
    environment:
      - NODE_PATH=src
      - NODE_ENV=test
      - NODE_CONFIG_DIR=apps/api/config

  geoprocessing:
    build:
      context: ./api
      dockerfile: geo.Dockerfile
      args:
        UID: 5000
        GID: 5000
    container_name: marxan-test-unit-geoprocessing
    command: test-unit
    user: "5000:5000"
    volumes:
      - ./api/apps:/opt/marxan-geoprocessing/apps
      - ./api/libs:/opt/marxan-geoprocessing/libs
    environment:
      - NODE_PATH=src
      - NODE_ENV=test
      - NODE_CONFIG_DIR=apps/geoprocessing/config
