test('foo', () => {
  const input = `
BLM 23532
NUMREPS 100
INPUTDIR input
PUNAME pu.dat
SPECNAME spec.dat
PUVSPRNAME puvspr.dat
BOUNDNAME bound.dat
OUTPUTDIR output
_CLOUD_SCENARIO Example scenario 1 Project 1 Org 1
_CLOUD_PROJECT Example Project 1 Org 1
_CLOUD_ORGANIZATION Example Org 1
_CLOUD_GENERATED_AT 2021-12-02T16:14:16.423Z
VERBOSITY 2
SCENNAME output
SAVESOLUTIONSMATRIX 3
SAVERUN 3
SAVEBEST 3
SAVESUMMARY 3
SAVESCEN 3
SAVETARGMET 3
SAVESUMSOLN 3
SAVELOG 3
SAVESNAPSTEPS 0
SAVESNAPCHANGES 0
SAVESNAPFREQUENCY 0
`;
  const expected = `
BLM 99
NUMREPS 100
INPUTDIR input
PUNAME pu.dat
SPECNAME spec.dat
PUVSPRNAME puvspr.dat
BOUNDNAME bound.dat
OUTPUTDIR output
_CLOUD_SCENARIO Example scenario 1 Project 1 Org 1
_CLOUD_PROJECT Example Project 1 Org 1
_CLOUD_ORGANIZATION Example Org 1
_CLOUD_GENERATED_AT 2021-12-02T16:14:16.423Z
VERBOSITY 2
SCENNAME output
SAVESOLUTIONSMATRIX 3
SAVERUN 3
SAVEBEST 3
SAVESUMMARY 3
SAVESCEN 3
SAVETARGMET 3
SAVESUMSOLN 3
SAVELOG 3
SAVESNAPSTEPS 0
SAVESNAPCHANGES 0
SAVESNAPFREQUENCY 0
`;
  const matcher = new RegExp(/BLM\s(.*)/);

  expect(input.replace(matcher, 'BLM 99')).toEqual(expected);
});
