export enum ClonePiece {
  ExportConfig = 'export-config',
  ProjectMetadata = 'project-metadata',
  ProjectCustomProtectedAreas = 'project-custom-protected-areas',
  ProjectCustomFeatures = 'project-custom-features',
  PlanningAreaGAdm = 'planning-area-gadm',
  PlanningAreaCustom = 'planning-area-custom',
  PlanningAreaCustomGeojson = 'planning-area-custom-geojson',
  PlanningUnitsGrid = 'planning-units-grid',
  PlanningUnitsGridGeojson = 'planning-units-grid-geojson',
  ScenarioMetadata = 'scenario-metadata',
  ScenarioPlanningUnitsData = 'scenario-planning-units-data',
  ScenarioRunResults = 'scenario-run-results',
  ScenarioProtectedAreas = 'scenario-protected-areas',
  ScenarioFeaturesData = 'scenario-features-data',
  FeaturesSpecification = 'feautures-specification',
}
