export enum ClonePiece {
  ExportConfig = 'export-config',
  ProjectMetadata = 'project-metadata',
  PlanningAreaGAdm = 'planning-area-gadm',
  PlanningAreaCustom = 'planning-area-custom',
  PlanningAreaCustomGeojson = 'planning-area-custom-geojson',
  PlanningAreaGrid = 'planning-area-grid',
  PlanningAreaGeojson = 'planning-area-grid-geojson',
  ScenarioMetadata = 'scenario-metadata',
  ScenarioPuData = 'scenario-pu-data',
  ScenarioRunResults = 'scenario-run-results',
  ProjectCustomProtectedAreas = 'project-custom-protected-areas',
  ScenarioProtectedAreas = 'scenario-protected-areas',
  UserUploadedFeatures = 'user-uploaded-features',
  FeaturesSpecification = 'feautures-specification',
}
