name: Build and publish container images for test jobs to GitHub Container Registry

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'staging'
      - 'production'
    paths:
      - 'api/**'
      - 'postgresql/**'
      - 'webshot/**'
      - '.github/**'
  pull_request:
  workflow_dispatch:
  workflow_call:
    outputs:
      api_image_tag:
        description: OCI image tag for the api image
        value: ${{ jobs.build_and_push_api.outputs.image_tag }}
      geoprocessing_image_tag:
        description: OCI image tag for the geoprocessing image
        value: ${{ jobs.build_and_push_geoprocessing.outputs.image_tag }}
      apidb_image_tag:
        description: OCI image tag for the apidb image
        value: ${{ jobs.build_and_push_apidb.outputs.image_tag }}
      geodb_image_tag:
        description: OCI image tag for the geodb image
        value: ${{ jobs.build_and_push_geodb.outputs.image_tag }}
      redis_image_tag:
        description: OCI image tag for the redis image
        value: ${{ jobs.build_and_push_redis.outputs.image_tag }}

env:
  REGISTRY: ghcr.io

jobs:

  build_and_push_api:
    name: Build and push API service container image to registry
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}
    env:
      REPOSITORY: marxan-api
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set registry namespace
        id: set_registry_namespace
        shell: bash
        run: |
          echo "registry_namespace=$(echo ${{ github.repository_owner }} | tr A-Z a-z)" >> $GITHUB_OUTPUT

      - name: Configure Docker metadata for image tags
        id: meta
        uses: docker/metadata-action@v4
        env:
          REGISTRY_NAMESPACE: ${{ steps.set_registry_namespace.outputs.registry_namespace }}
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{env.REGISTRY}}/${{env.REGISTRY_NAMESPACE}}/${{env.REPOSITORY}}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=sha

      - name: Build and push
        id: build_and_push
        uses: docker/build-push-action@v4
        with:
          context: ./api
          push: true
          file: api/api.Dockerfile
          tags: ${{ steps.meta.outputs.tags }}

  build_and_push_geoprocessing:
    name: Build and push Geoprocessing service container image to registry
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}
    env:
      REPOSITORY: marxan-geoprocessing
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set registry namespace
        id: set_registry_namespace
        shell: bash
        run: |
          echo "registry_namespace=$(echo ${{ github.repository_owner }} | tr A-Z a-z)" >> $GITHUB_OUTPUT

      - name: Configure Docker metadata for image tags
        id: meta
        uses: docker/metadata-action@v4
        env:
          REGISTRY_NAMESPACE: ${{ steps.set_registry_namespace.outputs.registry_namespace }}
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{env.REGISTRY}}/${{env.REGISTRY_NAMESPACE}}/${{env.REPOSITORY}}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=sha

      - name: Build and push
        id: build_and_push
        uses: docker/build-push-action@v4
        with:
          context: ./api
          push: true
          file: api/geo.Dockerfile
          tags: ${{ steps.meta.outputs.tags }}

  build_and_push_apidb:
    name: Build and push apidb service container image to registry
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}
    env:
      REPOSITORY: marxan-postgresql-api
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set registry namespace
        id: set_registry_namespace
        shell: bash
        run: |
          echo "registry_namespace=$(echo ${{ github.repository_owner }} | tr A-Z a-z)" >> $GITHUB_OUTPUT

      - name: Configure Docker metadata for image tags
        id: meta
        uses: docker/metadata-action@v4
        env:
          REGISTRY_NAMESPACE: ${{ steps.set_registry_namespace.outputs.registry_namespace }}
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{env.REGISTRY}}/${{env.REGISTRY_NAMESPACE}}/${{env.REPOSITORY}}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=sha

      - name: Build and push
        id: build_and_push
        uses: docker/build-push-action@v4
        with:
          context: ./postgresql
          push: true
          file: postgresql/apidb.Dockerfile
          tags: ${{ steps.meta.outputs.tags }}

  build_and_push_geodb:
    name: Build and push geodb service container image to registry
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}
    env:
      REPOSITORY: marxan-postgresql-geo-api
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set registry namespace
        id: set_registry_namespace
        shell: bash
        run: |
          echo "registry_namespace=$(echo ${{ github.repository_owner }} | tr A-Z a-z)" >> $GITHUB_OUTPUT

      - name: Configure Docker metadata for image tags
        id: meta
        uses: docker/metadata-action@v4
        env:
          REGISTRY_NAMESPACE: ${{ steps.set_registry_namespace.outputs.registry_namespace }}
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{env.REGISTRY}}/${{env.REGISTRY_NAMESPACE}}/${{env.REPOSITORY}}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=sha

      - name: Build and push
        id: build_and_push
        uses: docker/build-push-action@v4
        with:
          context: ./postgresql
          push: true
          file: postgresql/geodb.Dockerfile
          tags: ${{ steps.meta.outputs.tags }}

  build_and_push_redis:
    name: Build and push Redis service container image to registry
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}
    env:
      REPOSITORY: marxan-redis
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set registry namespace
        id: set_registry_namespace
        shell: bash
        run: |
          echo "registry_namespace=$(echo ${{ github.repository_owner }} | tr A-Z a-z)" >> $GITHUB_OUTPUT

      - name: Configure Docker metadata for image tags
        id: meta
        uses: docker/metadata-action@v4
        env:
          REGISTRY_NAMESPACE: ${{ steps.set_registry_namespace.outputs.registry_namespace }}
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{env.REGISTRY}}/${{env.REGISTRY_NAMESPACE}}/${{env.REPOSITORY}}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=sha

      - name: Build and push
        id: build_and_push
        uses: docker/build-push-action@v4
        with:
          context: ./redis
          push: true
          tags: ${{ steps.meta.outputs.tags }}
