name: Tests - API e2e tests
on:
  push:
    paths:
      - 'api/**'
      - 'geoprocessing/**'
      - '.github/**'
  pull_request:
  workflow_dispatch:

jobs:

  test-api-e2e:
    name: E2E tests - API
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        test-suite:
          - access-control
          - api-events
          - async-jobs-garbage-collector
          - business-critical
          - calculate-pu-protection-level
          - cloning
          - files-repository
          - implicit-permissions
          - integration
          - legacy-project-import
          - project
          - project-jobs-status
          - project-planning-areas-tiles
          - project-planning-units
          - project-protected-areas
          - scenario-cost-template
          - scenario-difference-map-tiles
          - scenario-features
          - scenario-input-files
          - scenario-locks
          - scenario-protected-areas
          - scenario-pu-change
          - scenario-run-results
          - scenarios
          - scenario-solutions
          - scenarios-pu-data
          - upload-feature

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run CI tests via make task
        run: JEST_TEST_PATH_PATTERN="${{ matrix.test-suite }}" make test-e2e-api environment=ci
