name: Tests - Geoprocessing unit tests
on:
  push:
    paths:
      - 'api/**'
      - 'geoprocessing/**'
      - '.github/**'
  workflow_dispatch:

jobs:

  test-geo-unit:
    name: Unit tests - Geoprocessing
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run Geoprocessing Unit Tests
        run: make test-unit-geo
