export type Tab =
  | 'protected-areas'
  | 'protected-areas-preview'
  | 'protected-areas-threshold'
  | 'cost-surface'
  | 'planning-unit-status'
  | 'features'
  | 'features-add'
  | 'features-target'
  | 'pre-gap-analysis'
  | 'advanced-settings'
  | 'overview'
  | 'blm-calibration'
  | 'solutions-overview'
  | 'target-achievement';
